services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: db_name       # Your database name
      POSTGRES_USER: username         # Your username
      POSTGRES_PASSWORD: password  # Your password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: